name: CI/CD for home work15

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  SALT: ${{ secrets.SALT }}


jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Install dependencies server
        run: |
         cd server
         npm ci

      - name: Install dependencies client
        run: |
         cd client
         npm ci
      
      - name: Run ESLint
        run: |
         cd server
         npm run lint
      
      - name: Run build
        run: |
         cd server
         npm start


