name: CI/CD for home work15

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build server:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
    - uses: actions/checkout@v2

    - name: Install dependencies
    - run: |
       cd server
       npm cli
	
