name: CI/CD for home work15

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build server:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: cd server & npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Run build
        run: npm run build


